[toolchain]

[features]
resolution = true
seeds = true
skip-lint = false

[[test.genesis_accounts]]
address = "11111111111111111111111111111111"
lamports = 1000000
owner = "11111111111111111111111111111111"
executable = false

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[programs.devnet]
academy = "11111111111111111111111111111111"

[programs.mainnet]
academy = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"
